// <auto-generated />
using System;
using FSH.Modules.Proxies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FS.Proxy.Migrations.PostgreSQL.Proxies
{
    [DbContext(typeof(ProxiesDbContext))]
    [Migration("20260902223839_InitialProxies")]
    partial class InitialProxies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("proxies")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("ApiClients", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.HealthCheckTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedBodyKeyword")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TestUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HealthCheckTargets", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.PolicyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("MinDistinctReporters")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PolicyProfiles", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveSyncFailures")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProtectedCredentials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderType");

                    b.ToTable("ProviderAccounts", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.Proxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastRenewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProtectedPassword")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ProviderAccountId", "ExternalId");

                    b.ToTable("Proxies", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ProxyTagAssignment", b =>
                {
                    b.Property<Guid>("ProxyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProxyId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProxyTagAssignments", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ProxyUsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("HealthCheckTargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProxyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedByApiClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProxyId", "OccurredAtUtc");

                    b.ToTable("ProxyUsageEvents", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.TagHealthCheckTargetAssignment", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HealthCheckTargetId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("HealthCheckTargetId");

                    b.ToTable("TagHealthCheckTargetAssignments", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.TagPolicyAssignment", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("PolicyProfileId");

                    b.ToTable("TagPolicyAssignments", "proxies");
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.Proxy", b =>
                {
                    b.HasOne("FSH.Modules.Proxies.Domain.ProviderAccount", null)
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ProxyTagAssignment", b =>
                {
                    b.HasOne("FSH.Modules.Proxies.Domain.Proxy", null)
                        .WithMany("TagAssignments")
                        .HasForeignKey("ProxyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSH.Modules.Proxies.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.ProxyUsageEvent", b =>
                {
                    b.HasOne("FSH.Modules.Proxies.Domain.Proxy", null)
                        .WithMany()
                        .HasForeignKey("ProxyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.TagHealthCheckTargetAssignment", b =>
                {
                    b.HasOne("FSH.Modules.Proxies.Domain.HealthCheckTarget", null)
                        .WithMany()
                        .HasForeignKey("HealthCheckTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FSH.Modules.Proxies.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.TagPolicyAssignment", b =>
                {
                    b.HasOne("FSH.Modules.Proxies.Domain.PolicyProfile", null)
                        .WithMany()
                        .HasForeignKey("PolicyProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FSH.Modules.Proxies.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Proxies.Domain.Proxy", b =>
                {
                    b.Navigation("TagAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
